# Generated by Django 3.1.14 on 2022-09-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_skills', models.CharField(max_length=1000)),
                ('soft_skills', models.CharField(max_length=1000)),
                ('desired_position', models.CharField(max_length=150)),
                ('desired_payment', models.IntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('desired_place_of_work', models.CharField(max_length=1000)),
                ('about_me', models.CharField(max_length=3000)),
                ('checkbox', models.CharField(max_length=255)),
                ('direction_of_activity', models.CharField(max_length=1000)),
                ('type_of_company', models.CharField(max_length=1000)),
                ('csv', models.CharField(max_length=1000)),
                ('resume', models.FileField(upload_to='resume/%Y/%m/%d')),
            ],
        ),
    ]
