# Generated by Django 3.1.14 on 2022-09-09 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('whom', models.CharField(max_length=255)),
                ('programming_language', models.CharField(max_length=255)),
                ('framework', models.CharField(max_length=255)),
                ('specialist_level', models.CharField(max_length=255)),
                ('payment_amount', models.IntegerField()),
                ('paymant', models.BooleanField(default=False)),
                ('job_description', models.TextField()),
                ('type_of_work', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('type_of_employment', models.CharField(max_length=30)),
                ('working_draft', models.CharField(max_length=255)),
                ('duration_of_work', models.CharField(max_length=255)),
                ('hard_skills', models.CharField(max_length=1000)),
                ('soft_skills', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=255)),
                ('quation1', models.CharField(max_length=150)),
                ('quation2', models.CharField(max_length=150)),
                ('quation3', models.CharField(max_length=150)),
                ('health', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('working_conditions', models.BooleanField(default=False)),
                ('education', models.BooleanField(default=False)),
                ('finance_and_guarantees', models.BooleanField(default=False)),
                ('entertainments', models.BooleanField(default=False)),
                ('transport', models.BooleanField(default=False)),
                ('job_manager', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephon', models.IntegerField()),
                ('responses', models.CharField(max_length=150)),
                ('receive_notifications', models.BooleanField(default=False)),
                ('archive_it', models.BooleanField(default=False)),
                ('when_to_publish', models.BooleanField(default=False)),
                ('automatic_notification', models.BooleanField(default=False)),
                ('additionally', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancyes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
